import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  sriaSidebar: [
    {
      type: 'doc',
      id: 'introduction',
      label: '★ Introduction',
      customProps: {
        icon: 'fa-regular fa-star',
      },
    },
    {
      type: 'category',
      label: '🚩 1. Applications & Opportunities',
      collapsed: true,
      customProps: {
        icon: 'fa-solid fa-flag',
      },
      link: {
        type: 'doc',
        id: 'applications/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '01-applications',
        },
      ],
    },
    {
      type: 'category',
      label: '⚙️ 2. Technical Outlook',
      collapsed: true,
      customProps: {
        icon: 'fa-solid fa-gear',
      },
      link: {
        type: 'doc',
        id: 'technology/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '02-technology',
        },
      ],
    },
    {
      type: 'category',
      label: '🌐 3. Socio-Economic Outlook',
      collapsed: true,
      customProps: {
        icon: 'fa-solid fa-globe',
      },
      link: {
        type: 'doc',
        id: 'socio-economic/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '03-socio-economic',
        },
      ],
    },
    {
      type: 'category',
      label: '🏛️ 4. European Context',
      collapsed: true,
      customProps: {
        icon: 'fa-solid fa-landmark',
      },
      link: {
        type: 'doc',
        id: 'context/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '04-context',
        },
      ],
    },
  ],
};

export default sidebars;
